feat: 엔티티 생성
toki0411/Classroom-Reservation pull request #1
Opened 2023-07-01 17:15 UTC by toki0411

2023-07-01 17:26 UTC, dkswnkk approved these changes
갈길이 멀지만 차근차근 해봅시다 수고했쓰

2023-07-01 17:26 UTC, dkswnkk commented on src/main/java/jpa/reservation/entity/Member.java
> +    private String Email;
카멜 케이스 사용!!
```java
private String email
```

2023-07-01 17:26 UTC, dkswnkk commented on src/main/java/jpa/reservation/entity/Professor.java
> +public class Professor extends Member{
요기
```java
public class Professor extends Member {
```
스페이스 하나 불편.. 

macOS: Cmd + Alt + L 쓰면 자동정렬됩니당

2023-07-01 17:26 UTC, dkswnkk commented on src/main/java/jpa/reservation/entity/Professor.java
> +    private Long professorNumber;
휴대폰 번호는 ```String```이 되어야 할거같은뎅?

010-xxxx-xxxx 처럼 - 가 들어갈 수도 있지만 정수타입으로 해버리면 맨앞에 0은 생략이 되어버리기 때문

2023-07-01 17:26 UTC, dkswnkk commented on src/main/java/jpa/reservation/entity/Reservation.java
> +    private Integer numberOfMember;  //인원수
Wrapper 클래스는 null이 들어갈 수 있는데, 인원수 같은 경우는 null이 들어갈 일이 있을까?

int로 해도 될듯~!

cc. https://velog.io/@conficker77/Java-Wrapper-class%EC%99%80-Primitive-type%EC%97%90-%EB%8C%80%ED%95%B4%EC%84%9C

2023-07-01 17:26 UTC, dkswnkk commented on src/main/java/jpa/reservation/entity/ReservationStatus.java
> +    RESERVATED, CANCEL
흠.. 요거도 ```RESERATED```로 했으면 ```CANCELED```가 되어야 하지 않을까?

2023-07-01 17:44 UTC, dkswnkk requested changes

2023-07-01 17:44 UTC, dkswnkk commented on src/main/java/jpa/reservation/repository/ClassroomRepository.java
> +    public void save(Classroom classroom){
밑에 MemberRepository에서는 아래처럼 getId를 반환해주던데 요기는 안해줘도 되남?
```java
    public Long save(Member member) {
        em.persist(member);
        return member.getId();
    }
```

2023-07-01 17:44 UTC, dkswnkk commented on src/main/java/jpa/reservation/repository/ReservationRepository.java
> +        em.persist(reservation);
요기도!

2023-07-01 17:44 UTC, dkswnkk commented on src/main/java/jpa/reservation/service/ReservationService.java
> +    public void cancelReservation(Long ReservationId){
ReservationId -> reservationId가 되어야 할 것 같습니다.

2023-07-01 17:44 UTC, dkswnkk commented on src/main/java/jpa/reservation/service/ReservationService.java
> +    public Long Reservation(Long memberId, Long classroomId, LocalDateTime startTime, LocalDateTime endTime, Integer numberOfMember){
메서드 명도 카멜 케이스를 준수합시당 자바에서 파스칼 케이스는 클래스, 인터페이스, Enum과 같은 파일 네이밍에만 적용하면 됩니다
cc. https://dkswnkk.tistory.com/539

2023-07-05 13:18 UTC, dkswnkk approved these changes

2023-07-05 13:18 UTC, dkswnkk commented on src/main/java/jpa/reservation/repository/ReservationRepository.java
> +        QReservation reservation = QReservation.reservation;
요것들 static import하면 다음과 같이 따로 선언하지 않아도 된당
mac 기준으로 option + enter 누르면 손쉽게 할 수 있음!
```java
package jpa.reservation.repository;

import com.querydsl.core.types.dsl.BooleanExpression;
import com.querydsl.jpa.impl.JPAQueryFactory;
import jpa.reservation.entity.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;
import org.springframework.util.StringUtils;

import javax.persistence.EntityManager;
import java.util.List;

import static jpa.reservation.entity.QMember.*;
import static jpa.reservation.entity.QReservation.*;

@Repository
@RequiredArgsConstructor
public class ReservationRepository {

    private final EntityManager em;

    public void save(Reservation reservation) {
        em.persist(reservation);
    }

    public Reservation findOne(Long id) {
        return em.find(Reservation.class, id);
    }

    public void cancel(Reservation reservation) {
        reservation.setStatus(ReservationStatus.CANCELED);
    }

    public List<Reservation> findAll(ReservationSearch reservationSearch) {
        JPAQueryFactory query = new JPAQueryFactory(em);
        return query.select(reservation)
                .from(reservation)
                .join(reservation.member, member)
                .where(statusEq(reservationSearch.getReservationStatus()),
                        nameLike(reservationSearch.getMemberName()))
                .limit(1000)
                .fetch();
    }

    private BooleanExpression statusEq(ReservationStatus statusCond) {
        if (statusCond == null) {
            return null;
        }
        return reservation.status.eq(statusCond);
    }

    private BooleanExpression nameLike(String nameCond) {
        if (!StringUtils.hasText(nameCond)) {
            return null;
        }
        return member.name.like(nameCond);
    }

}
```

2023-07-05 13:19 UTC, merged

2023-07-05 13:30 UTC, toki0411 commented
너무 고맙습니다 !!! ✨ 짱